# Generated by Django 4.0.6 on 2022-09-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('requred_grades', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
