# Generated by Django 4.0.6 on 2022-09-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_job_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Available Job'},
        ),
    ]
