# Generated by Django 4.0.6 on 2022-10-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0005_sendmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmail',
            old_name='user',
            new_name='users',
        ),
    ]
