# Generated by Django 4.0.6 on 2022-10-12 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resource', '0006_rename_user_sendmail_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmail',
            name='users',
        ),
        migrations.AddField(
            model_name='sendmail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
