# Generated by Django 4.0.6 on 2022-10-12 09:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0009_sendmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmail',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
