# Generated by Django 4.0.6 on 2022-10-18 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resource', '0011_traningcategory_traning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traningcategory',
            options={'verbose_name': 'Traning'},
        ),
        migrations.CreateModel(
            name='TraningApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('traning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.traning')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
