# Generated by Django 4.0.6 on 2022-10-18 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resource', '0013_alter_traningapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traningapplication',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
