# Generated by Django 4.0.6 on 2022-11-08 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resource', '0014_alter_traningapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traningapplication',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_traning', to=settings.AUTH_USER_MODEL),
        ),
    ]
