# Generated by Django 4.0.6 on 2022-10-11 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_user', '0012_course_user_course'),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate_user.course'),
        ),
    ]
