# Generated by Django 4.0.6 on 2022-10-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_notice_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='teacher/')),
                ('name', models.CharField(max_length=150)),
                ('facebook', models.URLField(max_length=250)),
                ('gmail', models.URLField(max_length=250)),
                ('twitter', models.URLField(max_length=250)),
                ('linkedin', models.URLField(max_length=250)),
            ],
        ),
    ]
