# Generated by Django 4.0.6 on 2022-11-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_teacher_description_teacher_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
