# Generated by Django 4.0.6 on 2022-11-21 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0009_whatsappgroup_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappgroup',
            name='User',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
