# Generated by Django 4.0.6 on 2022-11-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_whatsappgroup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='user/staff/')),
                ('description', models.TextField()),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
            ],
        ),
    ]
