# Generated by Django 3.2.16 on 2022-12-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About U'},
        ),
    ]
