# Generated by Django 4.0.6 on 2022-09-17 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_studentqualification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applyforjob',
            options={'verbose_name': 'Student Apply For Job'},
        ),
        migrations.RemoveField(
            model_name='applyforjob',
            name='user',
        ),
        migrations.AddField(
            model_name='applyforjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
