# Generated by Django 4.0.6 on 2022-09-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_applyforjob_date_applyforjob_interview_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applyforjob',
            options={'verbose_name': 'Job Application'},
        ),
    ]
