# Generated by Django 4.0.6 on 2022-09-18 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resource', '0004_alter_job_options'),
        ('student', '0005_alter_applyforjob_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforjob',
            name='job',
            field=models.ManyToManyField(related_name='jobs', to='human_resource.job'),
        ),
        migrations.AlterField(
            model_name='applyforjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='user_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentqualification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_qulification', to=settings.AUTH_USER_MODEL),
        ),
    ]
