# Generated by Django 4.0.6 on 2022-10-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_applyforjob_job_alter_applyforjob_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyForJob',
        ),
    ]
