# Generated by Django 4.0.6 on 2022-10-07 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_alter_job_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0010_delete_applyforjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='user/resume/')),
                ('date', models.DateField(blank=True, null=True)),
                ('interview_start_time', models.TimeField(blank=True, null=True)),
                ('interview_end_time', models.TimeField(blank=True, null=True)),
                ('job', models.ManyToManyField(related_name='jobs', to='human_resource.job')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='user_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Application',
            },
        ),
    ]
