# Generated by Django 4.0.6 on 2022-10-07 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_alter_job_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0011_applyforjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyforjob',
            name='job',
        ),
        migrations.AddField(
            model_name='applyforjob',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='job_in', to='human_resource.job'),
        ),
        migrations.RemoveField(
            model_name='applyforjob',
            name='user',
        ),
        migrations.AddField(
            model_name='applyforjob',
            name='user',
            field=models.ManyToManyField(related_name='user_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
