# Generated by Django 4.0.6 on 2022-10-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_applyforjob_job_applyforjob_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyforjob',
            name='resume',
        ),
    ]
