# Generated by Django 4.0.6 on 2022-10-09 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0013_remove_applyforjob_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforjob',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
