# Generated by Django 4.0.6 on 2022-10-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_applyforjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentqualification',
            name='course_type',
            field=models.CharField(blank=True, choices=[('10', '10'), ('12', '12'), ('GRADUATE', 'GRADUATE'), ('POST-GRADUATE', 'POST-GRADUATE')], max_length=150, null=True),
        ),
    ]
