# Generated by Django 4.0.6 on 2022-09-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profiel_pic',
            new_name='profile_pic',
        ),
    ]
