# Generated by Django 4.0.6 on 2022-09-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_user', '0002_rename_profiel_pic_user_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addres',
            options={'verbose_name': 'User Addres'},
        ),
    ]
