# Generated by Django 4.0.6 on 2022-09-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_user', '0006_alter_contact_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactDetails',
        ),
    ]
