# Generated by Django 4.0.6 on 2022-09-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_user', '0007_rename_contact_contactdetails'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contactdetails',
            managers=[
            ],
        ),
    ]
