# Generated by Django 4.0.6 on 2022-09-18 06:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_user', '0008_alter_contactdetails_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contactdetails',
            managers=[
                ('contact', django.db.models.manager.Manager()),
            ],
        ),
    ]
