# Generated by Django 4.0.6 on 2022-09-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_user', '0009_alter_contactdetails_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'verbose_name': 'Contact'},
        ),
    ]
